### ISSUE TITLE
Getting Authorization error while running the JiraZapi

### ISSUE THREAD

**Issue by NLRKUM1** [vkirankumar3090/zephyrWithCucumber#1]
Hi VKiran,
Thanks for creating such a nice project for updating Jira using ZApi. It made my work very much smoother.
  
I have updated all the details in property file and ran the job but now i am getting authorization error, so wanted to know if the authorization issue is JIRA or Zephyr ZAPI. 

error msg.
[66] [19/05/30 00:56:21] INFO Config: ------------------initilizing----------------
[40] [19/05/30 00:56:23] INFO ZephyrTestCaseManagementCloud: GET : InboundJaxrsResponse{ClientResponse{method=GET, uri=https://atradius-naa.atlassian.net/rest/api/2/project/TA, status=401, reason=Unauthorized}}
java.lang.Exception: Unable to connect to JIRA
	at com.Zapi.Utilities.ZephyrTestCaseManagementCloud.doGet(ZephyrTestCaseManagementCloud.java:42)
	at com.Zapi.Utilities.JiraAPI.getVersionId(JiraAPI.java:28)
	at com.Zapi.Utilities.Config.<init>(Config.java:53)
	at com.Zapi.Utilities.CucumberJsonDataExtractor.<init>(CucumberJsonDataExtractor.java:15)
	at com.Zapi.Utilities.ZephyrTestCaseManagementCloud.updateTestCaseAndStepStatus(ZephyrTestCaseManagementCloud.java:123)
	at test.sample.sample.Test.main(Test.java:11)
[57] [19/05/30 00:56:23] INFO Config: Unable to load properties file

**Comment by vkirankumar3090** [comment]
it's a issue with your JIRA token please check that.

**Comment by vkirankumar3090** [comment]
Please share me the applications.properties file i can check that

**Comment by NLRKUM1** [comment]
Below is the Property file details.


zapi.baseurl=https://prod-api.zephyr4jiracloud.com/connect
jira.baseurl=https://atradXXX-naa.atlassian.net
#generate this token by providing username:password in https://www.base64decode.org/ and encode it.
jira.authorization=5c891782722f2c4428813XXX
zapi.accesskey=amlyYTo4ZGUwMzgzMS04ZTU2LTRkYmQtYTUwZi0xMTkyNTc4ZWU1YWIgNWM4OTE3ODI3MjJmMmM0NDI4ODEzNzkwIFVTRVJfREVGQVVMVF9XXXXX
zapi.secretkey=NR-aBl_W3rIJw0hWSEDxnVVOEXpnUbpg8s4jTVkPXXX
zapi.userName=admin
#you can find this by navigate to your project in jira "https://company.atlassian.net/projects/<project.key>"
project.key=TA
#This can be find by navigation to your test cycle > click on execute of any test case now in url you can find the id.
project.id=Ad hoc
#This is test cycle name which need to be executed if the specified test cycle is not present in jira then it will create new test cycle with the given name.
testcycle.name=SharedComponents

#Related to release service call (Needs Admin access to create Release)
#This is relea Version name which need to be executed if the specified Release Version is not present in jira then it will create new Release Version with the given name.(for this it needs Administrator credentials)
release.version=v.1.0
released=true
release.startDate=2019-07-23
release.endDate=2019-07-25

**Comment by NLRKUM1** [comment]
You can close this issue . It is resolved after replacing JIRA token as password.

**Comment by NLRKUM1** [comment]
It is solved.
