### ISSUE TITLE
Getting org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by NLRKUM1** [vkirankumar3090/zephyrWithCucumber#2]
Hi Kiran,
Thanks for solving my login problem, Just to update you , from April this year 2019, There is change in login process to JIRA cloud using API, Now we have to use (Userid:JiraToken) encoded with base64 .  There update need to be made in your property file. 

Now after sucessful login i am getting below error.

org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at org.json.JSONArray.<init>(JSONArray.java:147)
	at com.Zapi.Utilities.JiraAPI.getVersionId(JiraAPI.java:29)
	at com.Zapi.Utilities.Config.<init>(Config.java:53)
	at com.Zapi.Utilities.CucumberJsonDataExtractor.<init>(CucumberJsonDataExtractor.java:15)
	at com.Zapi.Utilities.ZephyrTestCaseManagementCloud.updateTestCaseAndStepStatus(ZephyrTestCaseManagementCloud.java:123)
	at test.sample.sample.Test.main(Test.java:11)
[57] [19/06/06 22:17:59] INFO Config: Unable to load properties file
[139] [19/06/06 22:17:59] INFO ZephyrTestCaseManagementCloud: [Ljava.lang.StackTraceElement;@2931522b
[140] [19/06/06 22:17:59] INFO ZephyrTestCaseManagementCloud: Unable to Update the Test case and step status
------------------------------------------------------------------------
Need your help to fix this

**Comment by NLRKUM1** [comment]
Its was fixed after including correct version number

**Comment by naveenkumardp945** [comment]
Hi,

org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1].
How you fix this issue.
Please let me know. I am getting the above error when i try to get the information from JIRA using rest api.

Thanks
Naveen

**Comment by vkirankumar3090** [comment]
Hi naveenkumardp945,

Can you please share me your cucumber json report. Look like there is a issue in the report json file.

**Comment by rmmahajan** [comment]
Hi NLRKUM1,

If you could please tell where to add this version number because I am facing the same issue while using JIRA rest API.

**Comment by ezizrehimov** [comment]
which version need ?
